---
exclude_paths:
  - '**/node_modules/**'
  - '**/dist/**'
  - '**/static/**'
  - '**/.cache/**'
  - '**/vendor/**'
  - '**/benchmarks/**/*'
  - '*.yml'
  - '*.md'
  - '*.sassrc'
  - '*.json'
  - '*.sh'
  - '*.gitignore'
  - '*.json'
  - '*.lock'
  - '*.txt'
  - '*.xml'
  - '*.css'
  - '*.editorconfig'